# ruff.toml
line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "W", "I", "UP", "B", "PL"]
ignore = [
    "PLR0915", # Too many statements
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments
    "PLR0911", # Too many return statements
    "PLW0603", # Using global statement
    "PLR2004", # Magic value used in comparison
    "E501",    # Line too long
]

[format]
quote-style = "preserve"
