build:
  images:
  - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  options:
    logging: CLOUD_LOGGING_ONLY
    substitutionOption: ALLOW_LOOSE
  source:
    repoSource:
      branchName: ^main$
      projectId: analyse-hippique
      repoName: Hippique-Analyse-0925
    filename: cloudbuild.yaml
  substitutions:
    REPO_NAME: hippique-analyse-0925
    _AR_HOSTNAME: europe-west1-docker.pkg.dev
    _AR_PROJECT_ID: analyse-hippique
    _AR_REPOSITORY: cloud-run-source-deploy
    _DEPLOY_REGION: europe-west1
    _PLATFORM: managed
    _SERVICE_NAME: hippique-orchestrator
    _TRIGGER_ID: 6f2204c6-122e-4f2d-9988-a239019aca6b
  tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - hippique-orchestrator
createTime: '2025-10-31T12:30:41.146363454Z'
description: Build and deploy to Cloud Run service hippique-orchestrator on push to
  "^main$"
github:
  name: Hippique-Analyse-0925
  owner: francoisosmozis-hue
  push:
    branch: ^main$
id: 6f2204c6-122e-4f2d-9988-a239019aca6b
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: rmgpgab-hippique-orchestrator-europe-west1-francoisosmozis-hodk
resourceName: projects/analyse-hippique/locations/global/triggers/6f2204c6-122e-4f2d-9988-a239019aca6b
serviceAccount: projects/analyse-hippique/serviceAccounts/1084663881709-compute@developer.gserviceaccount.com
substitutions:
  REPO_NAME: hippique-analyse-0925
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_PROJECT_ID: analyse-hippique
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: europe-west1
  _PLATFORM: managed
  _SERVICE_NAME: hippique-orchestrator
  _TRIGGER_ID: 6f2204c6-122e-4f2d-9988-a239019aca6b
tags:
- gcp-cloud-build-deploy-cloud-run
- gcp-cloud-build-deploy-cloud-run-managed
- hippique-orchestrator
